## part1作业
### 谈谈你是如何理解JS异步编程的，EventLoop、消息队列都是做什么的，什么宏任务，什么是微任务？
```
答：
JS异步编程：异步模式是JS执行任务模式的一种，为了解决JS任务执行时阻塞任务的情况。
异步模式的特点就是下达这个任务开启的指令之后，就会继续往下执行，代码是不会在这一行等待任务的结束的。任务异步执行，在任务结束之后，回调函数会去帮我们执行想做的事情。异步编程一般是通过 callback 回调函数、事件发布/订阅、Promise 等来组织代码，本质都是通过回调函数来实现异步代码的存放与执行。
那这件想要做的事情其实就可以理解为回调函数。
Event Loop:事件循环，是指浏览器一种解决JS单线程运行时的一种机制。作用：负责监听调用栈和消息队列，一旦调用栈中的任务都已经结束了，事件循环就会从消息队列中取出第一个，压入到调用栈。
消息队列：也有人把消息队列称为回调队列。如果说调用栈是一个正在执行的工作表，消息队列就是一个待办的工作表，而js执行引擎就会先去做完调用栈中的任务，再通过事件循环去消息队列中再取一个任务过来继续去执行，以此类推，而这个过程中我们随时都可以往消息队列中去放一些任务，这些任务会在消息队列中排队等待事件循环。
宏任务：消息队列中的每个任务都是宏任务。

微任务：每个宏任务都有一个微任务队列，是在当前任务执行结束后需要立即执行的任务。微任务包含：Promise.then、MutaionObserver、process.nextTick(Node.js 环境)等。

```
### 代码题
一、将下面异步代码使用Promise的方式改进
```
setTimeout(function ()) {
    var a = 'hello'
    setTimeout(function () {
        var b = 'lagou'
        setTimeout(function () {
            var c = 'I ♥ U'
            console.log(a + b + c)
        }, 10)
    }, 10)
}, 10)
```
```
答：
function fn(value) {
   return new Promise((resolved, rejected) => {
      setTimeout(()=>{
         resolved(value + ' ')
      }, 10)
   });
}

fn().then(function () {
   return fn('hello')
}).then(value=> {
   return fn(value +'lagou')
}).then(value=> {
   return fn(value +'I ♥ U')
}).then(value=> {
   console.log(value)
})
```

```
二、基于以下代码完成下面的四个练习
```
const fp =  require('lodash/fp')
// 数据
// horsepower 马力，dollar_value 价格， in_stock 库存
const cars = [
    { name: 'Ferrari FF', horsepower: 660, dollar_value: 700000, in_stock: true },
    { name: 'Spyker C12 Zagato', horsepower: 650, dollar_value: 648000, in_stock: false },
    { name: 'Jaguar XKR-S', horsepower: 550, dollar_value: 132000, in_stock: false },
    { name: 'Audi R8', horsepower: 525, dollar_value: 114200, in_stock: false },
    { name: 'Aston Martin One-77', horsepower: 750, dollar_value: 1850000, in_stock: true },
    { name: 'Pagani Huayra', horsepower: 700, dollar_value: 1300000, in_stock: false },
]
```
练习1：使用函数组合fp.flowRight()重新实现下面这个函数
```
let isLastInStock = function (cars) {
    // 获取最后一条数据
    let last_car = fp.last(cars)
    // 获取最后一条数据的 in_stock 属性值
    return fp.prop('in_stock', last_car)
}
```
```
答：
let fr = fp.folwRight(fp.prop('in_stock'), fp.last);
```
练习2：使用fp.flowRight()、fp.prop()和fp.first()获取第一个car的name
```
let fr = fp.flowRight(fp.prop('name'), fp.first);
```
练习3：使用帮助函数_average重构averageDollarValue,使用函数组合的方式实现
```
let _average = function (xs) {
    return fp.reduce(fp.add, 0, xs) / xs.length
} // <-无需改动
let averageDollarValue = function (cars) {
    let dollar_values = fp.map(function (car) {
        return car.dollar_value
    }, cars)
    return _average(dollar_values)
} 
```
```
答：
let _average = function (xs) {
    return fp.reduce(fpadd, 0, xs) / xs.length
}

let averageDollarValue = function(cars) {
    let arr = fp.flowRhght(_average, fp.map((car) => {
        return car.dollar_value;
    }));
    return arr(cars);
}
```
练习4：使用flowRight写一个sanitizeNames()函数，返回一个下划线连接的小写字符串，把数组中的name转换为这种形式：例如：sanitizeNames(["Hello World"]) => ["hello_world"]
```
let _underscore = fp.replace(/\W+/g, ' ') // <--无须改动，并在sanitizeNames中使用它
```
```
答：
let _underScore = fp.replace(/\W+/g, '_');
function sanitizeNames() {
    return fp.folwRight(fp.map((name) => {
        _underScore(name)
    }));
}
```
三、基于下面提供的代码，完成后续的四个练习
```
// support.js
Class Container {
    static of(value) {
        return new Container(value)
    }
    constructor(value) {
        this._value =  value
    }
    map(fn) {
        return Container.of(fn(this._value))
    }
}
class Maybe {
    static of(x) {
        return new Maybe(x)
    }
    isNothing() {
        return this._value === null || this._value === undefined
    }
    constructor(x) {
        this._value =  x
    }
    map(fn) {
        return this.isNothing() ? this : Maybe.of(fn(this._value))
    }
}
module.exports = { Maybe, Container }
```
练习1：使用fp.add(x, y)和fp.map(f, x)创建一个能让functor里的值增加的函数ex1
```
//app.js
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let maybe = Maybe.of([5, 6, 1])
let ex1 = () => {
    // 你需要实现的函数
}
```
```
答：
let fn = fp.flowRight(fp.map(fp.add(num)));
return maybe.map(fn);
```
练习2：实现一个函数ex2,能够使用fp.first获取列表的第一个元素
```
// app.js
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let xs = Container.of(['do', 'ray', 'me', 'fa', 'so', 'la', 'ti', 'do'])
let ex2 = () => {
    // 你需要实现的函数
}
```
```
答：
return xs.map(fp.first)._value
```
练习3：实现一个函数ex3,使用safeProp和fp.first找到user的名字的首字母
```
// app.js
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let safeProp = fp.curry(function (x, o) {
    return Maybe.of(o[x])
})
let user = { id: 2, name: 'Albert' }
let ex3 = () => {
    // 你需要实现的函数
}
```
```
答：
return safeProp('name', user).map(fp.first)._value;
```
练习4：使用Maybe重写ex4,不要有if语句
```
// app.js
const fp = require('lodash/fp')
const { Maybe, Container } = require('./support')
let ex4 = function (n) {
    if (n) {
        return parseInt(n)
    }
}
```
```
答：
let ex4 = function(n) {
	let e1 = new MayBe(n);
	let e2 = e1.map(parseInt);
	return e2._value;
}
```
四、手写实现MyPromise源码
要求：尽可能还原Promise中的每一个API，并通过注释的方式描述思路和原理。
```
思路：

1.首先创建一个promise对象，用new；//  promise就是一个类，在执行的时候我们需要传递一个回调函数进去,这个回调函数我们把它称之为执行器，这个执行器会立即执行，也就是说当我们去new Promise的时候，这个回调函数会被立即调用
2. Promise中有三种状态，分别为成功fulfilled，失败 rejected，等待 pending  pending -> fulfilled pending -> rejected  一旦状态确定，便不可更改
3.resolve和reject函数是用来更改状态的
4. then方法内部做的事情就是判断状态，如果状态是成功，调用成功的回调函数，如果状态是失败，调用失败的回调函数 (then方法是被定义在原型对象中的) 
5. then成功回调有一个参数 表示成功之后的值，then失败回调有一个参数，表示失败的原因
6. 异步调用情况
7.then方法是可以被多次调用的
8.then方法是可以被链式调用的，后面then方法的回调函数拿到的值是上一个then方法的回调函数的返回值(分为两个步骤去做：1.实现then方法的链式调用 2.如何把上一个then方法的回调函数的返回值作为参数传递给下一个then方法的回调函数)
9.then的链式调用，返回情况：如果是普通值，那么可以直接调用resolve将该返回值传递给下一个promise对象;如果返回的是promise对象，那么需要先去查看返回的这个promise对象的状态，成功，调用resolve将成功的值传递给下一个promise对象，失败，调用reject将失败的结果传递给下一个promise对象
10. 自己返回自己，promise被循环调用报错情况处理（处理获取自己取不到的问题：将部分代码变成异步来解决）
11. 捕获错误以及then链式调用其他状态代码补充
12. then链式调用不传递任何参数，在最后一个then的回调函数里取到值(包括成功和失败)
13.Promise的all方法的实现 (一个类.all方法，那么all方法一定是个静态方法）;all实现时异步问题解决
14.Promise.resolve()方法
15.finally()方法;特点是：不管当前的promise对象最终的状态是成功还是失败，finally方法中的回调函数始终都会被执行一次；finally方法后面支持链式调用then方法来拿到当前这个promise对象最终返回的结果;finally方法是被定义在原型对象上的 (finally方法中的回调函数中有异步)
16.promise对象下的catch方法：用来处理当前这个promise对象，最终的状态为失败的情况的。(如果不传递失败回调，那么这个失败回调就会被catch方法所捕获)

promise原理代码

// 状态定义为常量：好处 1.复用 2.代码有提示
const PENDING = 'pending' // 等待
const FULFILLED = 'fulfilled' // 成功
const REJECTED = 'rejected' // 失败
class MyPromise {
    constructor (executor) { // executor 代表执行器
        // 捕获执行器错误
        try {
            executor(this.resolve, this.reject); // 执行器是立即执行的，这个执行器指的就是回调函数
        } catch (error) {
            this.reject(error);
        }
    }
    // promise状态 默认是等待
    status = PENDING; // 状态是每一个promise对象独有的，所以添加为实例状态
    // 成功之后的值
    value = undefined;
    // 失败之后的原因
    reason = undefined;
    // 成功的回调
    successCallback = [];
    // 失败的回调
    failCallback = [];
    resolve = value => { // 用箭头函数的原因：为了让内部的this指向promise类生成的这个实例对象（promise对象）
        // 如果状态不是等待，阻止代码向下执行
        if (this.status !== PENDING) return;
        // 将等待改为成功
        this.status = FULFILLED;
        // 保存成功之后的值
        this.value = value;
        // 判断 成功回调是否存在，存在，调用
        // this.successCallback && this.successCallback(this.value);
        // while (this.successCallback.length) this.successCallback.shift()(this.value);
        while (this.successCallback.length) this.successCallback.shift()();
    }
    reject = reason => {
         // 如果状态不是等待，阻止代码向下执行
         if (this.status !== PENDING) return;
         // 将等待改为失败
         this.status = REJECTED;
          // 保存失败之后的原因
        this.reason = reason;
         // 判断 失败回调是否存在，存在，调用
        //  this.failCallback && this.failCallback(this.reason);
        // while (this.failCallback.length) this.failCallback.shift()(this.reason);
        while (this.failCallback.length) this.failCallback.shift()();
    }
    then (successCallback, failCallback) {
        successCallback = successCallback ? successCallback : value => value;
        failCallback = failCallback ? failCallback : reason => { throw reason };
        let promise2 = new MyPromise((resolve, reject) => {
            // 判断状态
            if (this.status === FULFILLED) {
                setTimeout(() => {
                    try {
                        let x = successCallback(this.value);
                        // resolve(x);
                        // 判断x是普通值还是promise对象
                        // 如果是普通值， 直接调用resolve
                        // 如果是promise对象 查看promise对象返回的结果
                        // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
                        resolvePromise(promise2, x, resolve, reject);
                    } catch (error) {
                        reject(error);
                    }
                }, 0)
            } else if (this.status === REJECTED) {
                setTimeout(() => {
                    try {
                        let x = failCallback(this.reason);
                        // resolve(x);
                        // 判断x是普通值还是promise对象
                        // 如果是普通值， 直接调用resolve
                        // 如果是promise对象 查看promise对象返回的结果
                        // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
                        resolvePromise(promise2, x, resolve, reject);
                    } catch (error) {
                        reject(error);
                    }
                }, 0)
            } else {
                // pending 等待
                // 将成功回调和失败回调存储起来
                // this.successCallback = successCallback;
                // this.failCallback = failCallback;
                this.successCallback.push(() => {
                    setTimeout(() => {
                        try {
                            let x = successCallback(this.value);
                            // resolve(x);
                            // 判断x是普通值还是promise对象
                            // 如果是普通值， 直接调用resolve
                            // 如果是promise对象 查看promise对象返回的结果
                            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
                            resolvePromise(promise2, x, resolve, reject);
                        } catch (error) {
                            reject(error);
                        }
                    }, 0)
                });
                this.failCallback.push(() => {
                    setTimeout(() => {
                        try {
                            let x = failCallback(this.reason);
                            // resolve(x);
                            // 判断x是普通值还是promise对象
                            // 如果是普通值， 直接调用resolve
                            // 如果是promise对象 查看promise对象返回的结果
                            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
                            resolvePromise(promise2, x, resolve, reject);
                        } catch (error) {
                            reject(error);
                        }
                    }, 0)
                });
            }
        })
        return promise2;
    }
    finally (callback) {
        return this.then(value => {
            return MyPromise.resolve(callback()).then(() => value);
        }, reason => {
            MyPromise.resolve(callback()).then(() => { throw reason });
        })
    }
    catch (failCallback) {
       return this.then(undefined, failCallback);
    }
    static all (array) {
        let result = [];
        let index = 0;
        return new MyPromise((resolve, reject) => {
            function addData (key, value) {
                result[key] = value;
                index++;
                if (index === array.length) {
                    resolve(result);
                }
            }
            for (let i = 0; i < array.length; i++) {  
                let current = array[i];
                if (current instanceof MyPromise) {
                    // promise对象
                    current.then(value => addData(i, value), reason => reject(reason));
                } else {
                    // 普通值
                    addData(i, array[i]);
                }
            }
        })
        
    }
    static resolve (value) {
        if (value instanceof MyPromise) return value;
        return new MyPromise(resolve => resolve(value));
    }
}
function resolvePromise (promise2, x, resolve, reject) {
  if (promise2 === x) {
      return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
      //  return 是为了阻止程序向下运行
  }
  if (x instanceof MyPromise) {
    // promise对象
    // x.then(value => resolve(value), reason => reject(reason));
    x.then(resolve, reject);
  } else {
    // 普通值
    resolve(x);
  }
}
```